# Generated by Django 4.2 on 2023-06-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_module', '0002_news_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created_at',), 'verbose_name': 'خبر', 'verbose_name_plural': 'خبر ها'},
        ),
    ]
