# Generated by Django 4.2 on 2023-06-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'تصویر گالری', 'verbose_name_plural': 'تصاویر گالری'},
        ),
        migrations.AlterModelOptions(
            name='galleryvideo',
            options={'verbose_name': 'ویدیو گالری', 'verbose_name_plural': 'ویدیو های گالری'},
        ),
    ]
