# Generated by Django 4.2 on 2023-06-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0002_hyperlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthday',
            options={'ordering': ['birthday_date'], 'verbose_name': 'تولد', 'verbose_name_plural': 'تولد ها'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_date'], 'verbose_name': 'رویداد', 'verbose_name_plural': 'رویداد ها'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-created_at'], 'verbose_name': 'فایل ارسالی', 'verbose_name_plural': 'قایل های ارسالی'},
        ),
    ]
