# Generated by Django 4.2 on 2023-05-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='images/matplotlib')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
