# Generated by Django 4.2 on 2023-05-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0002_contactreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='image',
            field=models.ImageField(upload_to='images/matplotlib'),
        ),
    ]
