# Generated by Django 4.2 on 2023-05-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0003_alter_contact_phone_number_alter_contactreport_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactreport',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
