# Generated by Django 4.2 on 2023-05-26 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0004_alter_contactreport_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='agent',
        ),
    ]
