# Generated by Django 4.2 on 2023-05-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0005_remove_contact_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactreport',
            name='is_stabled',
            field=models.BooleanField(default=False),
        ),
    ]
