# Generated by Django 4.2 on 2023-06-10 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0012_user_administrative_department'),
        ('contact_module', '0006_contactreport_is_stabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='head_administrative_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_module.administrativedepartment'),
        ),
    ]
