# Generated by Django 4.2 on 2023-06-14 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0008_alter_contact_options_alter_contactreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='form',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='contact_module.contactformmodel'),
            preserve_default=False,
        ),
    ]
