# Generated by Django 4.2 on 2023-05-10 20:06

import account_module.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_userloggedout_userloggedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=1, upload_to='images/avatar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='national_code',
            field=models.CharField(default='0313304300', max_length=10, unique=True, validators=[account_module.validation.is_valid_iran_code]),
            preserve_default=False,
        ),
    ]
