# Generated by Django 4.2 on 2023-05-13 19:13

import account_module.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0006_user_birthday_date_alter_user_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(max_length=10, null=True, validators=[account_module.validation.is_valid_iran_code]),
        ),
    ]
