# Generated by Django 4.2 on 2023-06-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0008_alter_user_national_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leaving_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='recruitment_date',
            field=models.DateField(default='2022-02-12'),
            preserve_default=False,
        ),
    ]
