# Generated by Django 4.2 on 2023-06-01 10:19

import account_module.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0009_user_leaving_date_user_recruitment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(max_length=10, unique=True, validators=[account_module.validation.is_valid_iran_code]),
        ),
    ]
