# Generated by Django 4.2 on 2023-06-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0010_alter_user_national_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_head_department',
            field=models.BooleanField(default=False),
        ),
    ]
