# Generated by Django 4.2 on 2023-06-10 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0012_user_administrative_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_head_department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='administrative_department',
        ),
        migrations.CreateModel(
            name='AdministrativeDepartmentHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administrative_department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account_module.administrativedepartment')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='administrative_department_head',
            field=models.ManyToManyField(blank=True, null=True, to='account_module.administrativedepartmenthead'),
        ),
        migrations.AddField(
            model_name='user',
            name='administrative_department',
            field=models.ManyToManyField(to='account_module.administrativedepartment'),
        ),
    ]
