# Generated by Django 4.2 on 2023-06-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0013_remove_user_is_head_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrativedepartment',
            options={'verbose_name': 'دپارتمان اداری', 'verbose_name_plural': 'دپارتمان های اداری'},
        ),
        migrations.AlterModelOptions(
            name='administrativedepartmenthead',
            options={'verbose_name': 'سرپرست دپارتمان', 'verbose_name_plural': 'سرپرست های دپارتمان'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterModelOptions(
            name='userloggedin',
            options={'verbose_name': 'گزارش ورود', 'verbose_name_plural': 'گزارشات ورود'},
        ),
        migrations.AlterModelOptions(
            name='userloggedout',
            options={'verbose_name': 'گزارش خروح', 'verbose_name_plural': 'گزارشات خروج'},
        ),
    ]
