# Generated by Django 4.2 on 2023-06-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0014_alter_administrativedepartment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='administrative_department',
            field=models.ManyToManyField(blank=True, null=True, to='account_module.administrativedepartment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='recruitment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
